// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qmbsqkddochgabcotnuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFtYnNxa2Rkb2NoZ2FiY290bnVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MzA4NTksImV4cCI6MjA1ODQwNjg1OX0.AHxwD7FKEkQCdCDOFbagLkU7y-_SDQ75W9acnlle7Uo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);